// TODO: Insert description here. (generated by jimbankoski)

#ifndef VP9_ENCODER_VP9_CONTEXT_TREE_H_
#define VP9_ENCODER_VP9_CONTEXT_TREE_H_

#include "vp9/encoder/vp9_onyx_int.h"

void vp9_setup_pc_tree(VP9_COMP *cpi);
void vp9_free_pc_tree(VP9_COMP *cpi);

#endif /* VP9_ENCODER_VP9_CONTEXT_TREE_H_ */
